### ISSUE TITLE
Upgrade module dependencies to kubernetes 1.21.x

### ISSUE THREAD

**Issue by bjw-s** [k8s-at-home/dnsmadeeasy-webhook#12]
# Details

**Describe the solution you'd like:**

Currently, the Renovate PR's are failing CI, we should fix the project so that we can run the latest dependencies without breaking CI 😅

**Comment by bjw-s** [comment]
Still relevant. @angelnu Could you maybe take a look at this?

**Comment by angelnu** [comment]
Yes, still relevant @bjw-s - missed this one.

**Comment by bjw-s** [comment]
https://github.com/jetstack/cert-manager/pull/3926 Looks to have been merged :)

**Comment by angelnu** [comment]
Solved by https://github.com/k8s-at-home/dnsmadeeasy-webhook/commit/95aa07cfcb97c869d6c7f907225c29ccd343f3d8
