### ISSUE TITLE
Broken if a _acme-challenge record exists which isn't a TXT

### ISSUE THREAD

**Issue by taxilian** [k8s-at-home/dnsmadeeasy-webhook#45]
# Details

The code does not verify that found records are TXT records, so if you happen to have e.g. an A record of that same name then it returns that instead and then never succeeds. I know that seems like a silly thing to do, but in our case we have a domain which has a wildcard CNAME record on it -- the only way to keep cert-manager from following that CNAME is to have an A record in place so that it doesn't see it, but then the dnsme webhook pukes :-(

Even weirder, though I can't see where in the code this might be happening, I've actually had that CNAME get deleted a few times when using this with cert-manager.

I may take a stab at figuring it out, but I really don't know golang.

**Comment by angelnu** [comment]
Re-opening until @taxilian could confirm the latest dev (with the patch) to work for him. Then I will cut a new official release.

**Comment by angelnu** [comment]
verified
